<?php
function Account(){ return new \App\Models\Base\Account(); }
function AccountBalance(){ return new \App\Models\Base\AccountBalance(); }
function AccountContact(){ return new \App\Models\Base\AccountContact(); }
function AccountGroup(){ return new \App\Models\Base\AccountGroup(); }
function AccountMovement(){ return new \App\Models\Base\AccountMovement(); }
function AccountType(){ return new \App\Models\Base\AccountType(); }
function BankAccount(){ return new \App\Models\Base\BankAccount(); }
function BankMovement(){ return new \App\Models\Base\BankMovement(); }
function CashMovement(){ return new \App\Models\Base\CashMovement(); }
function CashType(){ return new \App\Models\Base\CashType(); }
function CreditCardInfo(){ return new \App\Models\Base\CreditCardInfo(); }
function Expense(){ return new \App\Models\Base\Expense(); }
function Income(){ return new \App\Models\Base\Income(); }
function IncomeExpenseCategory(){ return new \App\Models\Base\IncomeExpenseCategory(); }
function IncomeExpenseType(){ return new \App\Models\Base\IncomeExpenseType(); }
function Invoice(){ return new \App\Models\Base\Invoice(); }
function InvoiceDetail(){ return new \App\Models\Base\InvoiceDetail(); }
function InvoicePaymentMethod(){ return new \App\Models\Base\InvoicePaymentMethod(); }
function InvoiceSeries(){ return new \App\Models\Base\InvoiceSeries(); }
function InvoiceStatus(){ return new \App\Models\Base\InvoiceStatus(); }
function InvoiceType(){ return new \App\Models\Base\InvoiceType(); }
function Migration(){ return new \App\Models\Base\Migration(); }
function OnlinePaymentTransaction(){ return new \App\Models\Base\OnlinePaymentTransaction(); }
function Payment(){ return new \App\Models\Base\Payment(); }
function PaymentMethod(){ return new \App\Models\Base\PaymentMethod(); }
function PaymentProvider(){ return new \App\Models\Base\PaymentProvider(); }
function PaymentStatus(){ return new \App\Models\Base\PaymentStatus(); }
function Permission(){ return new \App\Models\Base\Permission(); }
function Product(){ return new \App\Models\Base\Product(); }
function ProductBrand(){ return new \App\Models\Base\ProductBrand(); }
function ProductCategory(){ return new \App\Models\Base\ProductCategory(); }
function ProductFeature(){ return new \App\Models\Base\ProductFeature(); }
function RefundTransaction(){ return new \App\Models\Base\RefundTransaction(); }
function Role(){ return new \App\Models\Base\Role(); }
function Settings(){ return new \App\Models\Base\Settings(); }
function StockCount(){ return new \App\Models\Base\StockCount(); }
function StockMovement(){ return new \App\Models\Base\StockMovement(); }
function StockWarehouse(){ return new \App\Models\Base\StockWarehouse(); }
function User(){ return new \App\Models\Base\User(); }
function UserActivityLog(){ return new \App\Models\Base\UserActivityLog(); }
function UserRole(){ return new \App\Models\Base\UserRole(); }
